### ISSUE TITLE
Issue in building the code

### ISSUE THREAD

**Issue by ayazalavi** [aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos#22]
Hi,

When I try to run the command "idf.py build" in project directory then I get following error and bunch of warnings:

`/Volumes/Projects/ESP-Projects/WebRTC-FREERTOS/main/lib/amazon-kinesis-video-streams-webrtc-sdk-c/src/include/kvs/common_defs.h:331:16: error: redefinition of typedef 'UINT32' with different type`

then I get 

```
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```

**Comment by dhornacek-mhs** [comment]
@ayazalavi Hey there, I remember having this problem when building with esp-idf v4.4 as well, did you find any solutions here?

**Comment by ayazalavi** [comment]
> @ayazalavi Hey there, I remember having this problem when building with esp-idf v4.4 as well, did you find any solutions here?

Yes I disabled datachannel in cmake file and changed status constant to different name in entire codebase. Lots of work I did to achieve this.

**Comment by dhornacek-mhs** [comment]
Gotcha, I had a feeling I would have to change all the STATUS names. Thanks for the reply
