### ISSUE TITLE
Build issues with the repo

### ISSUE THREAD

**Issue by vikramdattu** [aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos#34]
Hello Kinesis team,

As reported in [this](https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/issues/22) issue, the code is not buildable as is on provided IDF version or not on any IDF version for that matter.

Please find the attached patches I have added to be able to build the code:
Patch for this repo: 
[rename_to_KIN_STATUS_build_issues.patch](https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/files/12102201/rename_to_KIN_STATUS_build_issues.patch)

Patch for [amazon-kinesis-video-streams-webrtc-sdk-c submodule repo ](https://github.com/iotlabtpe/amazon-kinesis-video-streams-webrtc-sdk-c.git):  (Present in `main/lib/` folder)
[rename_STATUS_TO_KIN_STATUS.patch](https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/files/12102203/rename_STATUS_TO_KIN_STATUS.patch)

After applying these patches, I am now able to build the code.

Please suggest a best way to fix/integrate above patches to aforementioned repos.

**Comment by unicornss** [comment]
Thanks @vikramdattu.

**Comment by vikramdattu** [comment]
@unicornss I have raised another issue here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/246

Please do check. If required, I can raise one here.

**Comment by vikramdattu** [comment]
Closing the issues, since with the latest change and patches build goes through.
