### ISSUE TITLE
Not able to stream to Web Test Page

### ISSUE THREAD

**Issue by vikramdattu** [aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos#35]
Hello,

I have diligently followed the setup instructions outlined in the README documentation. As evidenced by the LOGs, the Session Description Protocol (SDP) messages are being exchanged as expected. However, there appears to be an issue with the streaming process from my ESP32 device to the web interface.

For your convenience, I have attached the log files named "device_side_logs_webrtc_for_freertos.log" and "aws_webrtc_js.log." These files provide additional information regarding the situation.

It was my anticipation that the provided sample example would function seamlessly with minimal alterations to the code. Regrettably, I have dedicated approximately two full days to this endeavor. During this time, I have engaged in extensive debugging and iterative modifications, eventually reaching the current state of progress. I now feel stuck and am not able to have any progress!

Your assistance in addressing this matter would be greatly appreciated.

[device_side_logs_webrtc_for_freertos.log](https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/files/12171062/device_side_logs_webrtc_for_freertos.log)
[aws_webrtc_js.log](https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/files/12171065/aws_webrtc_js.log)

Regards,

**Comment by vikramdattu** [comment]
Hello @ycyang1229 any update on this?

**Comment by zhichent** [comment]
Are you following instructions and use patch from pull request 33? I have tested using us-west-2, it worked fine.

**Comment by codingspirit** [comment]
@vikramdattu @zhichent The #33 has been merged into main branch

**Comment by vikramdattu** [comment]
@codingspirit thanks, the I am able to get the video stream with these fixes.
